# Default profile - works for any project
# Override values as needed for your project

project:
  name: "{{PROJECT_NAME}}"
  repo_owner: "{{REPO_OWNER}}"
  default_branch: "main"

# Workspace configuration (new workspace model)
# Set installation_mode to "workspace" when applying to a separate workspace directory
workspace:
  installation_mode: "embedded"  # "embedded" (in-project) or "workspace" (separate directory)
  target_project_path: ""        # Required for workspace mode: absolute path to target project
  workspace_name: ""             # Optional: name of workspace directory

workflow:
  skills_dir: ".claude/skills"
  codex_skills_dir: ".codex/skills"
  commands_dir: ".claude/commands"
  docs_dir: "docs"
  phase_prefix: "phase-"
  phase_count: 6
  codex_bot_user: "chatgpt-codex-connector[bot]"

labels:
  ready: "agent-ready"
  in_progress: "in-progress"
  needs_review: "needs-review"
  blocked: "blocked"

commands:
  test: "echo 'No test command configured'"
  test_unit: ""
  test_integration: ""
  lint: "echo 'No lint command configured'"

# Worker agent configuration
worker:
  max_retries: 3        # Max attempts to fix quality gate failures
  max_issues: 10        # Max issues to process per worker session
  poll_interval: 60     # Seconds between issue queries when none available

commit:
  types:
    - feat
    - fix
    - docs
    - refactor
    - test
    - chore
  scope_required: false

branch:
  pattern: "<issue>-<title-slug>"
  max_length: 60

output:
  skills:
    - check-reviews
    - address-review
    - claim-issue
    - check-workflow
    - submit-pr
    - worker
    - sync-skills
    - telemetry-init
    - telemetry-report
    - telemetry-aggregate
    - README.md
  commands:
    - check-reviews
    - address-review
    - claim-issue
    - check-workflow
    - submit-pr
    - worker
    - sync-skills
    - telemetry-init
    - telemetry-report
    - telemetry-aggregate
  docs:
    - QUICK-REFERENCE.md
    - FAQ-AGENTS.md
    - CODEBASE-MAP.md
  security:
    - SECURITY-CHECKLIST.md
  roles:
    - WORKER-ROLE.md
