#!/usr/bin/env bash
# migrate-to-workspace.sh
# Migrate an embedded toolkit installation to workspace model
#
# Usage: migrate-to-workspace.sh <source-project-path> <workspace-path>
#
# This script:
# 1. Creates a new workspace directory
# 2. Copies skills and commands from source project
# 3. Generates workspace-config pointing to source project
# 4. Prompts before removing old files from source project

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SOURCE_PROJECT="${1:-}"
WORKSPACE_PATH="${2:-}"

usage() {
    echo "Usage: migrate-to-workspace.sh <source-project-path> <workspace-path>"
    echo ""
    echo "Migrate an embedded toolkit installation to the workspace model."
    echo ""
    echo "Arguments:"
    echo "  source-project-path  Path to project with embedded toolkit"
    echo "  workspace-path       Path for new workspace directory"
    echo ""
    echo "Example:"
    echo "  ./migrate-to-workspace.sh ~/myproject ~/myproject-workspace"
    echo ""
    echo "The workspace model keeps your target project clean by placing"
    echo "all toolkit infrastructure in a separate workspace directory."
}

if [[ -z "$SOURCE_PROJECT" ]] || [[ -z "$WORKSPACE_PATH" ]]; then
    usage
    exit 1
fi

if [[ "$SOURCE_PROJECT" == "--help" ]] || [[ "$SOURCE_PROJECT" == "-h" ]]; then
    usage
    exit 0
fi

# Resolve to absolute paths
SOURCE_PROJECT=$(realpath "$SOURCE_PROJECT")
WORKSPACE_PATH=$(realpath -m "$WORKSPACE_PATH")

echo -e "${BLUE}Migrating from embedded to workspace model...${NC}"
echo ""
echo "  Source project: $SOURCE_PROJECT"
echo "  New workspace:  $WORKSPACE_PATH"
echo ""

# Validate source project
if [[ ! -d "$SOURCE_PROJECT" ]]; then
    echo -e "${RED}Error: Source project directory does not exist: $SOURCE_PROJECT${NC}"
    exit 1
fi

if [[ ! -d "$SOURCE_PROJECT/.git" ]]; then
    echo -e "${RED}Error: Source project is not a git repository${NC}"
    exit 1
fi

if [[ ! -d "$SOURCE_PROJECT/.claude/skills" ]]; then
    echo -e "${RED}Error: Source project does not have .claude/skills directory${NC}"
    echo "This doesn't look like a project with the toolkit installed."
    exit 1
fi

# Validate workspace path
if [[ -d "$WORKSPACE_PATH" ]]; then
    if [[ -d "$WORKSPACE_PATH/.claude" ]]; then
        echo -e "${RED}Error: Workspace already exists and has .claude directory${NC}"
        exit 1
    fi
    echo -e "${YELLOW}Warning: Workspace directory already exists${NC}"
    read -p "Continue and add toolkit files? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 0
    fi
fi

# Get repository info from source project
echo "Fetching repository information..."
cd "$SOURCE_PROJECT"

REPO_OWNER=$(gh repo view --json owner --jq '.owner.login' 2>/dev/null) || {
    echo -e "${RED}Error: Could not get repository owner. Is gh CLI authenticated?${NC}"
    exit 1
}
REPO_NAME=$(gh repo view --json name --jq '.name' 2>/dev/null) || {
    echo -e "${RED}Error: Could not get repository name${NC}"
    exit 1
}
DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")

echo "  Repository: $REPO_OWNER/$REPO_NAME"
echo "  Default branch: $DEFAULT_BRANCH"
echo ""

# Create workspace directory structure
echo "Creating workspace directory structure..."
mkdir -p "$WORKSPACE_PATH/.claude"
mkdir -p "$WORKSPACE_PATH/.codex"

# Copy skills
echo "Copying skills..."
cp -r "$SOURCE_PROJECT/.claude/skills" "$WORKSPACE_PATH/.claude/"
echo -e "  ${GREEN}Copied .claude/skills/${NC}"

# Copy commands if they exist
if [[ -d "$SOURCE_PROJECT/.claude/commands" ]]; then
    cp -r "$SOURCE_PROJECT/.claude/commands" "$WORKSPACE_PATH/.claude/"
    echo -e "  ${GREEN}Copied .claude/commands/${NC}"
fi

# Copy other .claude files
for file in toolkit-version settings.local.json; do
    if [[ -f "$SOURCE_PROJECT/.claude/$file" ]]; then
        cp "$SOURCE_PROJECT/.claude/$file" "$WORKSPACE_PATH/.claude/"
        echo -e "  ${GREEN}Copied .claude/$file${NC}"
    fi
done

# Create symlink for codex
ln -sf ../.claude/skills "$WORKSPACE_PATH/.codex/skills"
echo -e "  ${GREEN}Created .codex/skills symlink${NC}"

# Generate workspace config
echo ""
echo "Generating workspace configuration..."
cat > "$WORKSPACE_PATH/.claude/workspace-config" <<EOF
# Claude Workflow Toolkit - Workspace Configuration
# Generated by migrate-to-workspace.sh on $(date +%Y-%m-%d)

# Required: Absolute path to the target project
TARGET_PROJECT_PATH="$SOURCE_PROJECT"

# Required: GitHub repository information
TARGET_REPO_OWNER="$REPO_OWNER"
TARGET_REPO_NAME="$REPO_NAME"

# Required: Default branch for the target project
TARGET_DEFAULT_BRANCH="$DEFAULT_BRANCH"

# Optional: Toolkit source for update checks
TOOLKIT_SOURCE="${HOME}/claude-workflow-toolkit"

# Metadata
WORKSPACE_CREATED="$(date +%Y-%m-%d)"
INSTALLATION_MODE="workspace"
EOF
echo -e "  ${GREEN}Created .claude/workspace-config${NC}"

# Update toolkit-version if it exists
if [[ -f "$WORKSPACE_PATH/.claude/toolkit-version" ]]; then
    if ! grep -q "INSTALLATION_MODE" "$WORKSPACE_PATH/.claude/toolkit-version"; then
        echo 'INSTALLATION_MODE="workspace"' >> "$WORKSPACE_PATH/.claude/toolkit-version"
        echo -e "  ${GREEN}Updated toolkit-version with INSTALLATION_MODE${NC}"
    fi
fi

# Generate WORKSPACE.md
WORKSPACE_NAME=$(basename "$WORKSPACE_PATH")
cat > "$WORKSPACE_PATH/WORKSPACE.md" <<EOF
# Workflow Workspace for $REPO_NAME

This workspace manages Claude Code and Codex workflows for:

| Setting | Value |
|---------|-------|
| **Target Project** | \`$SOURCE_PROJECT\` |
| **Repository** | \`$REPO_OWNER/$REPO_NAME\` |
| **Default Branch** | \`$DEFAULT_BRANCH\` |

## Usage

Run skills from this workspace directory:

\`\`\`bash
cd $WORKSPACE_PATH
/check-reviews
/claim-issue 42
/check-workflow
/submit-pr
\`\`\`

Or from anywhere using --project flag:

\`\`\`bash
$WORKSPACE_PATH/.claude/skills/check-reviews
$WORKSPACE_PATH/.claude/skills/claim-issue --project $SOURCE_PROJECT 42
\`\`\`

## Skill Reference

| Priority | Skill | Description |
|----------|-------|-------------|
| 1 | \`/check-reviews\` | Detect unaddressed review feedback |
| 2 | \`/address-review <pr>\` | Address review feedback |
| 3 | \`/claim-issue <issue>\` | Claim issue and create branch |
| 4 | \`/check-workflow\` | Validate workflow state |
| 5 | \`/submit-pr\` | Create PR and update labels |

**Workflow Priority:** Always check for reviews before starting new work!

## Configuration

The workspace is configured in \`.claude/workspace-config\`:

\`\`\`bash
TARGET_PROJECT_PATH="$SOURCE_PROJECT"
TARGET_REPO_OWNER="$REPO_OWNER"
TARGET_REPO_NAME="$REPO_NAME"
TARGET_DEFAULT_BRANCH="$DEFAULT_BRANCH"
\`\`\`

Edit this file if the target project path changes.

---
*Migrated from embedded installation on $(date +%Y-%m-%d)*
EOF
echo -e "  ${GREEN}Created WORKSPACE.md${NC}"

echo ""
echo -e "${GREEN}Workspace created successfully!${NC}"
echo ""

# Interactive cleanup of source project
echo -e "${BLUE}Cleanup Options${NC}"
echo ""
echo "The following directories can be removed from the source project:"
echo "  - $SOURCE_PROJECT/.claude/skills/"
echo "  - $SOURCE_PROJECT/.claude/commands/"
echo "  - $SOURCE_PROJECT/.codex/"
echo ""

cleanup_dir() {
    local dir="$1"
    local desc="$2"

    if [[ -d "$dir" ]] || [[ -L "$dir" ]]; then
        echo -e "${YELLOW}Remove $desc?${NC}"
        echo "  Path: $dir"
        read -p "  Remove? (y/N) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -rf "$dir"
            echo -e "  ${GREEN}Removed${NC}"
        else
            echo "  Skipped"
        fi
        echo ""
    fi
}

cleanup_dir "$SOURCE_PROJECT/.claude/skills" ".claude/skills/"
cleanup_dir "$SOURCE_PROJECT/.claude/commands" ".claude/commands/"
cleanup_dir "$SOURCE_PROJECT/.codex" ".codex/"

# Check if .claude directory is now empty (except toolkit-version)
remaining_files=$(find "$SOURCE_PROJECT/.claude" -type f ! -name "toolkit-version" 2>/dev/null | wc -l)
if [[ "$remaining_files" -eq 0 ]]; then
    echo -e "${YELLOW}Remove entire .claude directory?${NC}"
    echo "  (Only toolkit-version remains)"
    read -p "  Remove? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$SOURCE_PROJECT/.claude"
        echo -e "  ${GREEN}Removed .claude directory${NC}"
    fi
fi

echo ""
echo -e "${GREEN}Migration complete!${NC}"
echo ""
echo "Next steps:"
echo ""
echo "  1. Start using the workspace:"
echo "     cd $WORKSPACE_PATH"
echo "     /check-reviews"
echo ""
echo "  2. Optional: Add workspace to your shell profile:"
echo "     alias myproject-work='cd $WORKSPACE_PATH'"
echo ""
